# Generated by Django 2.1.5 on 2020-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocksl',
            fields=[
                ('name', models.CharField(default='', max_length=30)),
                ('exchange', models.CharField(default='', max_length=100)),
                ('ticker', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
