# Generated by Django 2.1.5 on 2020-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksl',
            name='label',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
