# Generated by Django 2.1.5 on 2020-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_stocksl_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksl',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
